Repository nv-morpheus/utilities, pull requests merged in 2023-08, with the labels that each got.

#45 Adopt pybind11 v2.10.4
  cmake/morpheus_utils/package_config/pybind11/Configure_pybind11.cmake
Labels: non-breaking, 3 - Ready for Review, improvement

#52 Revert installing pybind11 via conda and patch the dec_ref method
  cmake/morpheus_utils/package_config/pybind11/Configure_pybind11.cmake
  cmake/morpheus_utils/package_config/pybind11/patches/gil_dec_ref.patch
Labels: bug, non-breaking, 3 - Ready for Review

#54 Use `copy-pr-bot`
  .github/copy-pr-bot.yaml
  .github/ops-bot.yaml
Labels: non-breaking, improvement
