Repository nv-morpheus/utilities, pull requests merged in 2025-02, with the labels that each got.

#94 bugfix: fix python import for version check
  ci/release/update-version.sh
Labels: bug, non-breaking

#92 [RELEASE] utilities v25.02.00
  CHANGELOG.md
  ci/release/download_deps_lib.py
  ci/runner/README.md
  ci/runner/build_and_push.sh
  cmake/morpheus_utils/package_config/indicators/Configure_indicators.cmake
  cmake/morpheus_utils/package_config/mrc/Configure_mrc.cmake
  cmake/morpheus_utils/package_config/register_api.cmake
Labels: ! - Release

#98 Chore: remove unused parameters from `register_api.cmake` functions
  cmake/morpheus_utils/environment_config/rapids_cmake/register_api.cmake
Labels: bug, breaking

#99 Chore: update `Configure_mrc.cmake` to not list `MRC_USE_CONDA` option
  cmake/morpheus_utils/package_config/mrc/Configure_mrc.cmake
Labels: bug, breaking

#95 Adopt Rapids 25.02
  ci/runner/README.md
  cmake/morpheus_utils/package_config/cccl/Configure_cccl.cmake
Labels: non-breaking, 3 - Ready for Review, feature request

#100 Fix bug ensuring all architectures are added to the docker manifest
  ci/runner/build_and_push.sh
Labels: bug, non-breaking, 3 - Ready for Review

#101 Adopt Pybind11 2.12
  cmake/morpheus_utils/package_config/pybind11/Configure_pybind11.cmake
  cmake/morpheus_utils/package_config/pybind11/patches/gil_dec_ref.patch
  cmake/morpheus_utils/python/python_module_tools.cmake
Labels: non-breaking, 3 - Ready for Review, feature request
